---
- name: my test playbok
  hosts: all
  become: true
   
  tasks:
  - name: install java on RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on Debian
    apt: 
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat 
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz
      dest: /opt
       
  - name: Extract Tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.99.tar.gz
      dest: /opt
      remote_src: true

  - name: change pormissions
    file:
      path: /opt/apache-tomcat-8.5.99/bin/startup.sh
      mode: 0777

  - name: start tomcat
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.99/bin 
